### BUILD

FROM python:3.8-alpine
WORKDIR /var/app
RUN apk add --no-cache gcc musl-dev linux-headers
COPY ./requirements.txt /var/app/requirements.txt
RUN pip install -r /var/app/requirements.txt

### RUNTIME
ENV FLASK_APP=/var/app/web.py
ENV FLASK_RUN_HOST=0.0.0.0

ENV TZ "Etc/UTC"
ENV PATH /usr/local/bin:$PATH
ENV       PYTHONPATH        "${PYTHONPATH}:/var/app"


EXPOSE 3333
COPY . /var/app

CMD ["flask", "run"]